spring:
  redis:
    host: 192.168.1.4
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 10
    timeout: 1000